### ISSUE TITLE
AutoDrive Course Editor

### ISSUE THREAD

**Issue by gabaon** [Stephan-S/FS19_AutoDrive#1097]
with version 1.0.7.1, the editor no longer works.
will you fix the bug?
thanks for developing autodrive

Regards,
Gabaon

**Comment by Iwan1803** [comment]
What doesn't work? Any error message? Logifle?

**Comment by raupach** [comment]
ActionCommand: Load
Root element :AutoDrive
----------------------------

Current Element :waypoints
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at de.adEditor.AutoDriveEditor.loadFile(AutoDriveEditor.java:297)
        at de.adEditor.EditorListener.actionPerformed(EditorListener.java:58)
        at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
        at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
        at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
        at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
        at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6636)
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
        at java.desktop/java.awt.Component.processEvent(Component.java:6401)
        at java.desktop/java.awt.Container.processEvent(Container.java:2263)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5012)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2762)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by raupach** [comment]
Ich war da eh gerade am schrauben (siehe pull request). Der Fehler ist mir erst aber gar nicht aufgefallen, da ich noch die alte Version verwendet habe. Hat sich wohl das XML geändert....

**Comment by raupach** [comment]
Das Tag <markerID> gibt es nicht mehr.

**Comment by Stephan-S** [comment]
Ja genau, da die Live Berechnung nun Standard ist, sind die berechneten Navigationsdaten (waypoint.marker) rausgeflogen, was die Dateien deutlich entschlankt hat.
@raupach Vielen Dank für deine Mitarbeit. Ich schau mir den Pull Request morgen Abend an und werde ihn dann gerne übernehmen, inklusive maven Integration :-)

**Comment by auddie2015** [comment]
> 
> 
> What doesn't work? Any error message? Logifle?

It is not saving. It wants to save as an image then it throws an error.

ActionCommand: Load
Root element :AutoDrive
----------------------------

Current Element :waypoints
Loaded config for map: Sample_Mod_Map_1
Editor has no map file for map: Sample_Mod_Map_1
ActionCommand: Load Image
ActionCommand: Save
SaveMap called
java.lang.NullPointerException
        at com.sun.org.apache.xerces.internal.dom.CoreDocumentImpl.renameNode(Unknown Source)
        at AutoDriveEditor.saveMap(AutoDriveEditor.java:628)
        at EditorListener.actionPerformed(EditorListener.java:32)
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
Done

**Comment by raupach** [comment]
> Ja genau, da die Live Berechnung nun Standard ist, sind die berechneten Navigationsdaten (waypoint.marker) rausgeflogen, was die Dateien deutlich entschlankt hat.

Dann müßte der Editor die markerID auch nicht mehr lesen oder schreiben und der Code dort könnte auch ersatzlos gestrichen werden? Oder werden dort noch zusätzliche Berechnungen mit der markerID gemacht? Ich könnte mir das ja mal ansehen.
Grüße Oliver.

**Comment by raupach** [comment]
Well, it looks pretty good. I have fixed the bug in my repository in the branch 'fix_NPE_cause_of_missing_markerID'. Who is interested can have a look there. There is also a working AD.jar. I have only commented it out in the source code. So it is only a "QuickAndDirty Test".
https://github.com/raupach/FS19_AutoDrive/tree/fix_NPE_cause_of_missing_markerID

**Comment by auddie2015** [comment]
> 
> 
> Well, it looks pretty good. I have fixed the bug in my repository in the branch 'fix_NPE_cause_of_missing_markerID'. Who is interested can have a look there. There is also a working AD.jar. I have only commented it out in the source code. So it is only a "QuickAndDirty Test".
> https://github.com/raupach/FS19_AutoDrive/tree/fix_NPE_cause_of_missing_markerID

Version 8 Update 241 will not run it. It says your compiler is newer? It's on my end I am sure but which JAVA should I be using? (I get mine from java.com)

**Comment by raupach** [comment]
I have compiled it with Java 11.

**Comment by PHansen940** [comment]
This worked totally fine for me.

Downloaded Raupach's version and Java 11

My issue: Nothing happens when I click save. Changed even the file name. No new file was created.

**Comment by raupach** [comment]
When you click on save, a dialog window should open. There you can choose the file name. Sometimes it might happen that this window appears behind another window or on a second monitor.

**Comment by PHansen940** [comment]
I know, the window appears. I click on "Save" - window closes. File not save. With new name . no new file created

**Comment by auddie2015** [comment]
> 
> 
> I know, the window appears. I click on "Save" - window closes. File not save. With new name . no new file created

Did you run it with the cmd so you can see the error log? I posted above about not saving and getting an error in the console.  The save error is the only one I was having. I am able to load and edit just fine in the release version. I just can't save anything.

**Comment by PHansen940** [comment]
Well, shit

C:\Users\Admin\Desktop\AD_Editor>java.exe -jar -Xms1024m -Xmx1024m .\AD.Jar
Error: opening registry key 'Software\JavaSoft\Java Runtime Environment'
Error: could not find java.dll
Error: Could not find Java SE Runtime Environment.

I reinstalled Java, no changes. I understand why I cant save, but how to solve. Google entries are quite complex to understand. I dont know what to add or change with regedit

**Comment by raupach** [comment]
I think this has nothing to do with AutoDrive. Java is not properly installed here. A good test is: open CMD and run "java -version".  For me it looks like this:

java version "13.0.2" 2020-01-14
Java(TM) SE Runtime Environment (build 13.0.2+8)
Java HotSpot(TM) 64-Bit Server VM (build 13.0.2+8, mixed mode, sharing)

Maybe you have more than one java-version installed? This is always bad. If this is the case, please uninstall ALL versions and install a current version:
https://www.oracle.com/java/technologies/javase-jdk13-downloads.html

**Comment by PHansen940** [comment]
C:\Users\Admin\Desktop\AD_Editor>java.exe -jar -Xms1024m -Xmx1024m .\AD.Jar
Der Befehl "java.exe" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

C:\Users\Admin\Desktop\AD_Editor>pause
Drücken Sie eine beliebige Taste . . .

Tjo, nu streikt er ganz :-D

**Comment by PHansen940** [comment]
Hab 8 deinstalliert
11 deinstalliert und 
13 installiert

Nu weiß ich auch nicht weiter

**Comment by raupach** [comment]
Ja, war bei mir auch. Nach der Installation ist Java bei Windows nicht im Suchpfad (PATH). Ich habe hier mal eine Anleitung zur Installation von Java gefunden:
https://tubemint.com/install-java-jdk/
Für dich wäre es hier ab "Add Java JDK 13 to system path" wichtig.

**Comment by PHansen940** [comment]
Das hat funktioniert

Bei Klick auf Save


ActionCommand: Save
SaveMap called
java.lang.NullPointerException
        at de.adEditor.AutoDriveEditor.saveMap(AutoDriveEditor.java:461)
        at de.adEditor.EditorListener.actionPerformed(EditorListener.java:30)
        at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
        at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
        at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
        at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
        at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6636)
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
        at java.desktop/java.awt.Component.processEvent(Component.java:6401)
        at java.desktop/java.awt.Container.processEvent(Container.java:2263)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5012)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2762)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by raupach** [comment]
Was machst du denn genau? Ich bin in den Tiefen dieses Editors noch nicht so drin...
Ich mache es immer so: 
1) Programm starten
2) Load Config (Im Dialog z.B. AutoDrive_Felsbrunn_config.xml auswählen)
3) Etwas editieren: z.B. Move Nodes, Connect Nodes,... usw
4) Save (wieder AutoDrive_Felsbrunn_config.xml auswählen)

**Comment by auddie2015** [comment]
If this helps, my antivirus has ransomware protection in it and it sometimes blocks programs from accessing My Documents (where the game saves). I checked to see if that was it and can say it is not. 

Sorry, I am not a programmer of even the modest kind so just trying to be helpful in any way I can.

**Comment by hectordc5** [comment]
I think i found why Course Editor is not saving the XML file. The updated XML's are missing   <Recalculation>true</Recalculation> inside the XML. I added the setting within the XML and it saves the file. I have not tested in game though.

**Comment by PHansen940** [comment]
Datei nicht gespeichert :-(

**Comment by PHansen940** [comment]
> 
> 
> Was machst du denn genau? Ich bin in den Tiefen dieses Editors noch nicht so drin...
> Ich mache es immer so:
> 
>     1. Programm starten
> 
>     2. Load Config (Im Dialog z.B. AutoDrive_Felsbrunn_config.xml auswählen)
> 
>     3. Etwas editieren: z.B. Move Nodes, Connect Nodes,... usw
> 
>     4. Save (wieder AutoDrive_Felsbrunn_config.xml auswählen)

Exactly like this! Ive tried "save as..." as well. Doesnt work either

**Comment by PHansen940** [comment]
> 
> 
> I think i found why Course Editor is not saving the XML file. The updated XML's are missing `<Recalculation>true</Recalculation>` within the file. I added the setting to the XML file and it saves successfully. I have not tested in game though.

Did that - not working



> 
> 
> If this helps, my antivirus has ransomware protection in it and it sometimes blocks programs from accessing My Documents (where the game saves). I checked to see if that was it and can say it is not.
> 
> Sorry, I am not a programmer of even the modest kind so just trying to be helpful in any way I can.

Checked - not working

**Comment by PHansen940** [comment]
Tried a different map (Felsbrunn) - same result. Everything works fine. But it does not save the file.

Moved the editor on the hardrive
Installed different versions of Java
Tried the original editor / and Raupach's

Next step: different computer - what may be a a little bit difficult because I dont have one

**Comment by hectordc5** [comment]
> ``

> File not saved :-(
> 
> Attached XML and map as .png - Maybe someone else can try and give feedback? Just to make sure its on my side not the editor's
> 
> Thanks a lot for the support
> 
> [Hof_Bergmann_AD.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/4229383/Hof_Bergmann_AD.zip)

Found your problem. It was the name of the file. The problem was in the lettering. Your file `Autodrive_HOF_BERGMANN_config` must have capital letters `**AutoDrive**`. Also, the `<Recalculation>true</Recalculation>` must be added in the XML in order for it to save, as the AutoDriveEditor.java looks for that line:

`            Node AutoDrive = doc.getFirstChild();
            Element root = doc.getDocumentElement();
            Node recalculation = doc.getElementsByTagName("Recalculation").item(0);
            recalculation.setTextContent("true");`

**Comment by PHansen940** [comment]
YES! Thank you very much, that worked for me

Thank you very very much

And have a nice day

**Comment by raupach** [comment]
I think the editor needs some more rework... I have some spare time right now and could do something.

**Comment by Stephan-S** [comment]
@raupach Gladly, I'm just removing the references to the old 'markerID' entries which are now no longer needed since 1.0.7.1
Feel free to improve upon everything you see fit :-)

**Comment by auddie2015** [comment]
> 
> 
> I think the editor needs some more rework... I have some spare time right now and could do something.

Thank you! I drive like a drunk monkey in the game and the editor is vital to avoid traffic accidents when I start using the paths. LOL

**Comment by auddie2015** [comment]
I still can't get this to work. It runs without error and it loads the map image but it does not load the course file and it seems that it then freeze because I cannot move the map around or zoom in or out. 

I have installed JDK 13. javac -version shows it installed. 

Do I need to remake my course files or load them into the game and replace the init one made with the one in the saved game folder?

**Comment by raupach** [comment]
It's a bug. I already fixed it, but in the meantime please always load the config first and then the map image.

**Comment by auddie2015** [comment]
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
[INFO ] 2020-03-05 18:17:23.906 [AWT-EventQueue-0] AutoDriveEditor - AutoDrive start.............................................................................................
[INFO ] 2020-03-05 18:17:26.052 [AWT-EventQueue-0] EditorListener - ActionCommand: Load
[INFO ] 2020-03-05 18:17:41.582 [AWT-EventQueue-0] AutoDriveEditor - loadFile: X:\Libraries\Documents\My Games\FarmingSimulator2019\savegame1\AutoDrive_Sosnovka_config.xml
[INFO ] 2020-03-05 18:17:41.588 [AWT-EventQueue-0] AutoDriveEditor - Root element :AutoDrive
[ERROR] 2020-03-05 18:17:41.590 [AWT-EventQueue-0] AutoDriveEditor - null
java.lang.NullPointerException: null
        at de.adEditor.AutoDriveEditor.loadXmlConfigFile(AutoDriveEditor.java:403) ~[AD.jar:?]
        at de.adEditor.AutoDriveEditor.loadConfigFile(AutoDriveEditor.java:271) ~[AD.jar:?]
        at de.adEditor.EditorListener.actionPerformed(EditorListener.java:60) ~[AD.jar:?]
        at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967) ~[?:?]
        at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308) ~[?:?]
        at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405) ~[?:?]
        at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262) ~[?:?]
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279) ~[?:?]
        at java.awt.Component.processMouseEvent(Component.java:6636) ~[?:?]
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3342) ~[?:?]
        at java.awt.Component.processEvent(Component.java:6401) ~[?:?]
        at java.awt.Container.processEvent(Container.java:2263) ~[?:?]
        at java.awt.Component.dispatchEventImpl(Component.java:5012) ~[?:?]
        at java.awt.Container.dispatchEventImpl(Container.java:2321) ~[?:?]
        at java.awt.Component.dispatchEvent(Component.java:4844) ~[?:?]
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918) ~[?:?]
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547) ~[?:?]
        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488) ~[?:?]
        at java.awt.Container.dispatchEventImpl(Container.java:2307) ~[?:?]
        at java.awt.Window.dispatchEventImpl(Window.java:2762) ~[?:?]
        at java.awt.Component.dispatchEvent(Component.java:4844) ~[?:?]
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772) ~[?:?]
        at java.awt.EventQueue$4.run(EventQueue.java:721) ~[?:?]
        at java.awt.EventQueue$4.run(EventQueue.java:715) ~[?:?]
        at java.security.AccessController.doPrivileged(AccessController.java:391) [?:?]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) ~[?:?]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95) ~[?:?]
        at java.awt.EventQueue$5.run(EventQueue.java:745) ~[?:?]
        at java.awt.EventQueue$5.run(EventQueue.java:743) ~[?:?]
        at java.security.AccessController.doPrivileged(AccessController.java:391) [?:?]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) [?:?]
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:742) [?:?]
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) [?:?]
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) [?:?]
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) [?:?]
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) [?:?]
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:?]
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) [?:?]
