### ISSUE TITLE
[BUG] Course Editor

### ISSUE THREAD

**Issue by bishop1806** [Stephan-S/FS19_AutoDrive#1303]
Good day!

Course Editor crashed during launch. Java version 1.8 (build 1.8.0_241-b07) installed. I reinstall Java, to be shure, but same result occured.

C:\Users\olega\Documents\FS19_AutoDrive-master\AutoDrive Course Editor>java.exe -jar -Xms1024m -Xmx1024m .\AD.Jar
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: de/adEditor/AutoDriveEditor has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)

C:\Users\olega\Documents\FS19_AutoDrive-master\AutoDrive Course Editor>pause

**Comment by raupach** [comment]
You need Java version greater than 11. Please uninstall the old version completely before.

**Comment by bishop1806** [comment]
Hi! Thanks for quick respond!

Problem solved, I install Java 13. Maybe will be better to put some disclaimer about, because I, as simple user, never know about version greater than automaticaly offered by Oracle.

Thanks!
Oleg

**Comment by raupach** [comment]
At the moment the external editor is subject to major changes. There will be a better manual for it soon. If you have any ideas or suggestions for improvement, let us know!

**Comment by bishop1806** [comment]
Firt of all I like to say, that you make great work, thanks, but I use Course Editor, because in last version of AD disappear buttons for ingame course editing. and using of key combination a bit unsusual for me.
