### ISSUE TITLE
[BUG] AD Editor - java error - not launching

### ISSUE THREAD

**Issue by rogeriodec** [Stephan-S/FS19_AutoDrive#1307]
**AutoDrive Version:** 1.1.0.2
**Release or Custom Zip:** Release  
**Map (If applicable):** 
**Vehicle / Type (If applicable):**   
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
I'm using Windows 10 x64.
I downloaded the lastest AD Editor version from Github, now every time I try to launch AD.Jar, I get:
 
![image](https://user-images.githubusercontent.com/11199752/78510293-892eb600-776a-11ea-8599-ae1ea8163f54.png)

![image](https://user-images.githubusercontent.com/11199752/78510297-93e94b00-776a-11ea-9b32-f8dbcde0589f.png)

When I run "Open Editor with Console to see errors.cmd": 

**C:\Users\Rogerio\Desktop\AutoDrive Course Editor>java.exe -jar -Xms1024m -Xmx1024m .\AD.Jar
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: de/adEditor/AutoDriveEditor has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)

C:\Users\Rogerio\Desktop\AutoDrive Course Editor>pause**

Here my current XML:
[AutoDrive_Felsbrunn_config.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/4434927/AutoDrive_Felsbrunn_config.zip)

My java is up to date.

How to solve this?

**Comment by Firefall666** [comment]
I have the same problem :-(

**Comment by raupach** [comment]
You need Java version greater than 11. Please uninstall the old version completely before.

**Comment by rogeriodec** [comment]
Thank you!
