### ISSUE TITLE
Course Editor:  "The AutoDrive config could not be saved"

### ISSUE THREAD

**Issue by Troopersan** [Stephan-S/FS19_AutoDrive#1727]
Hi guys
I'm having a problem using the Course Editor when I try to save de course. I get this error message "The AutoDrive config could not be saved". Initially I was trying with a big network I downloaded for Felsbrunn. Then I tried with my own saved course with only 2 destinations points and the same issue occurs. I'm using AutoDrive 1.1.0.7 and the latest Course Editor.

This is the log file:

[INFO ] 2020-12-27 09:12:30.288 [AWT-EventQueue-0] AutoDriveEditor - AutoDrive start.............................................................................................
[INFO ] 2020-12-27 09:12:32.511 [AWT-EventQueue-0] EditorListener - ActionCommand: Load
[INFO ] 2020-12-27 09:12:52.499 [AWT-EventQueue-0] AutoDriveEditor - loadFile: D:\Games\FS19 mods\Autodrive\Test\AutoDrive_config.xml
[INFO ] 2020-12-27 09:12:52.514 [AWT-EventQueue-0] AutoDriveEditor - Root element :AutoDrive
[INFO ] 2020-12-27 09:12:52.514 [AWT-EventQueue-0] AutoDriveEditor - Current Element :waypoints
[INFO ] 2020-12-27 09:12:52.521 [AWT-EventQueue-0] AutoDriveEditor - Loaded config for map: AutoDrive
[INFO ] 2020-12-27 09:12:52.521 [AWT-EventQueue-0] AutoDriveEditor - Editor has no map file for map: AutoDrive
[INFO ] 2020-12-27 09:12:52.521 [AWT-EventQueue-0] AutoDriveEditor - loadFile end.
[INFO ] 2020-12-27 09:12:59.803 [AWT-EventQueue-0] EditorListener - ActionCommand: Load Image
[INFO ] 2020-12-27 09:13:56.353 [AWT-EventQueue-0] EditorListener - ActionCommand: Remove Nodes
[INFO ] 2020-12-27 09:14:06.070 [AWT-EventQueue-0] EditorListener - ActionCommand: Save
[INFO ] 2020-12-27 09:14:06.070 [AWT-EventQueue-0] AutoDriveEditor - SaveMap called
[ERROR] 2020-12-27 09:14:06.086 [AWT-EventQueue-0] AutoDriveEditor - begin 10, end 9, length 20
java.lang.StringIndexOutOfBoundsException: begin 10, end 9, length 20
	at java.lang.String.checkBoundsBeginEnd(String.java:3319) ~[?:?]
	at java.lang.String.substring(String.java:1874) ~[?:?]
	at de.adEditor.AutoDriveEditor.saveXmlConfig(AutoDriveEditor.java:616) ~[AD.jar:?]
	at de.adEditor.AutoDriveEditor.saveMap(AutoDriveEditor.java:458) [AD.jar:?]
	at de.adEditor.EditorListener.actionPerformed(EditorListener.java:28) [AD.jar:?]
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967) [?:?]
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308) [?:?]
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405) [?:?]
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262) [?:?]
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279) [?:?]
	at java.awt.Component.processMouseEvent(Component.java:6635) [?:?]
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3342) [?:?]
	at java.awt.Component.processEvent(Component.java:6400) [?:?]
	at java.awt.Container.processEvent(Container.java:2263) [?:?]
	at java.awt.Component.dispatchEventImpl(Component.java:5011) [?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2321) [?:?]
	at java.awt.Component.dispatchEvent(Component.java:4843) [?:?]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918) [?:?]
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547) [?:?]
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488) [?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2307) [?:?]
	at java.awt.Window.dispatchEventImpl(Window.java:2772) [?:?]
	at java.awt.Component.dispatchEvent(Component.java:4843) [?:?]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772) [?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:721) [?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:715) [?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) [?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95) [?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:745) [?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:743) [?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) [?:?]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:742) [?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:?]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) [?:?]
[INFO ] 2020-12-27 09:15:53.991 [AWT-EventQueue-0] AutoDriveEditor - SaveMap called
[ERROR] 2020-12-27 09:15:53.991 [AWT-EventQueue-0] AutoDriveEditor - begin 10, end 9, length 20
java.lang.StringIndexOutOfBoundsException: begin 10, end 9, length 20
	at java.lang.String.checkBoundsBeginEnd(String.java:3319) ~[?:?]
	at java.lang.String.substring(String.java:1874) ~[?:?]
	at de.adEditor.AutoDriveEditor.saveXmlConfig(AutoDriveEditor.java:616) ~[AD.jar:?]
	at de.adEditor.AutoDriveEditor.saveMap(AutoDriveEditor.java:458) [AD.jar:?]
	at de.adEditor.AutoDriveEditor$1.windowClosing(AutoDriveEditor.java:81) [AD.jar:?]
	at java.awt.Window.processWindowEvent(Window.java:2078) [?:?]
	at javax.swing.JFrame.processWindowEvent(JFrame.java:298) [?:?]
	at java.awt.Window.processEvent(Window.java:2037) [?:?]
	at java.awt.Component.dispatchEventImpl(Component.java:5011) [?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2321) [?:?]
	at java.awt.Window.dispatchEventImpl(Window.java:2772) [?:?]
	at java.awt.Component.dispatchEvent(Component.java:4843) [?:?]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772) [?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:721) [?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:715) [?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) [?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95) [?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:745) [?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:743) [?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) [?:?]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:742) [?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:?]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) [?:?]

Hope you can help me with that.

**Comment by Axel32019** [comment]
Hello @Troopersan ,
The external editor might not be compatible with the new data structure of AD, please use the ingame editor meanwhile.

**Comment by Troopersan** [comment]
Thank you @Axel32019 .
At least I know that it was not my setup that was causing the issue.
I had a lot of editing to do on the config file so I did a workaround. I used the old style config file to edit and save which worked. Then I pasted that old style edited file to the savegame folder which was then converted automatically to the new style. All tested and working now.

**Comment by Axel32019** [comment]
You're welcome. If OK you might close this.

**Comment by Troopersan** [comment]
Shouldn't this issue be added as a bug? The issue is not solved. I managed to workaround the issue but it is not a practical solution in case I had to edit the file again. It would be nice to be able use the Course Editor tool with latest release of AutoDrive the proper way. Please let me know if you still would like me to close the issue.

**Comment by raupach** [comment]
I will adapt the editor to the new format in the next few days.

**Comment by Troopersan** [comment]
Great thank you. That will be very nice.

**Comment by raupach** [comment]
In fact, the change was small and easy to implement. For this reason it is now already done and I have created a PullRequest.
In the meantime you can test the version from my repository: https://github.com/raupach/FS19_AutoDrive/tree/fix/%231727-AutoDrive_config_changed/AutoDrive%20Course%20Editor
