### ISSUE TITLE
Autodrive course editor not save any changes.

### ISSUE THREAD

**Issue by badfly** [Stephan-S/FS19_AutoDrive#521]
Good day! I apologize for the errors, I use google translator. The problem is that the course editor does not save any changes and does not create a file when creating a new one. I am attaching a video.
[Video](https://youtu.be/GcQRwtA_t0c)

**Comment by geo-luchs** [comment]
Hi, 
Did you downloaded the  latest AD.jar?
Im using the Course  Editor from Time to Time, and it Works vor me fine

**Comment by Stephan-S** [comment]
Hey,
can you try saving it to a different location. Like for example your home folder?
Maybe it would need access to write to C:\ directly and instead of showing you the error, it just doesn't do anything

**Comment by badfly** [comment]
### Hi,
Did you downloaded the latest AD.jar?

Yes, lastest

### 
Hey,
can you try saving it to a different location. Like for example your home folder?

I tried saving to my Desktop folder and on disk "D". Nothing changed.

**Comment by worker2419** [comment]
Hallo Stephan,
leider das gleiche Problem, Version ist die wo die 16 Fach Map Änderung enthalten ist. Datei sicherheitshalber im Spiel neu erstellt, Anpassungen im Editor gemacht und Save gedrückt. Egal was ich versuche. Anderer Name, gleicher Name, anderes Verzeichnis, kein Erfolg. Anbei die XML und das PNG
[Suedhemmern.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3649068/Suedhemmern.zip)

**Comment by worker2419** [comment]
**Update: Editor läuft (Was habe ich getan) Last dem Editor Zeit**
1. Auf einem Laufwerk mit Schreibrechten einen Ordner angelegt Name FS19_AutoDrive_Editor
2 Aus der Master ZIP den Ordner AutoDrive Course Editor kopiert und die Leerzeichen aus dem Ordnernamen entfernt. Dann im Unterordner src\mapImages die PNG Datei eingefügt.
Diese Datei ist in der ZIP Datei eurer Map und hat dort immer den Namen pda_map_H.dds. Diese Datei exportieren und mit einem Bildbearbeitungsprogramm öffnen und als PNG abspeichern, Name ohne Leerzeichen z.B. Meine Map.PNG
3. Aus der Master ZIP den Ordner courses kopiert und einen Unterordner angelegt. Z.B meinemap Name ohne Leerzeichen
4. Aus dem aktuellem Savegame die Datei AutoDrive_xxxxxxxx_config.xml in den angelegten Unterordner kopiert xxxxx= Name der Map
5. Datei AD.jar gestartet

In der ZIP Datei als Hilfe die Datei Aufruf.cmd. Startet Ihr den Editor darüber zeigt das DOS Fenster die Schritte, die das Programm macht, aber auch Fehler, wenn es nicht klappt.

**Update: Editor is running (What have I done) editor need time to work**
1. created a folder on a drive with write access Name FS19_AutoDrive_Editor
2 Copy the AutoDrive Course Editor folder from the Master ZIP and remove the spaces from the folder name. Then insert the PNG file into the subfolder src\mapImages.
This file is in the ZIP file of your map and always has the name pda_map_H.dds. Export this file and open it with an image editor and save it as PNG, name without spaces e.g. MyMap.PNG
Copy the folder courses from the Master ZIP and create a subfolder. E.g. mymap name without spaces
4. copies the file AutoDrive_xxxxxxxx_config.xml from the current savegame into the created subfolder xxxxx= name of the map
5. file AD.jar started

In the ZIP file as help the file Aufruf.cmd. If you start the editor above, the DOS window shows the steps the program does, but also errors if it doesn't work.
Translation by deepl

[Aufruf.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3664172/Aufruf.zip)

**Comment by badfly** [comment]
> worker2419

Thank you! I determined that when using the editor, it is necessary that the name of the opened file does not contain Russian (or could any other than English) characters. otherwise it turns out this:
`SaveMap called
java.net.MalformedURLException: unknown protocol: d
        at java.net.URL.<init>(Unknown Source)
        at java.net.URL.<init>(Unknown Source)
        at java.net.URL.<init>(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLVersionDetector.determineDocVersion(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(Unknown Source)
        at javax.xml.parsers.DocumentBuilder.parse(Unknown Source)
        at AutoDriveEditor.saveMap(AutoDriveEditor.java:405)
        at EditorListener.actionPerformed(EditorListener.java:30)
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)`

When saving, you can use any language. Author, please correct this, because the game changes the names of the cards depending on the country. And I would add the utility to the archive with the editor for debug))
